#ifndef TOKEN_H_INCLUDED
#define TOKEN_H_INCLUDED

#define TK_ID			                        "identificador"
#define TK_COMENTARIO 	                        "comentario"
#define TK_BLOCO_COMENTARIO 	                "bloco_comentario"
#define TK_VALOR_STRING                         "valor_string"
#define TK_VALOR_CHAR                           "valor_char"
#define TK_ABRE_PARENTESES                      "abre_parentese"
#define TK_FECHA_PARENTESES                     "fecha_parentese"
#define TK_ABRE_CHAVETA                         "abre_chaveta"
#define TK_FECHA_CHAVETA                        "fecha_chaveta"
#define TK_ABRE_COLCHETES                       "abre_colchetes"
#define TK_FECHA_COLCHETES                      "fecha_colchetes"
#define TK_DOIS_PONTOS                          "dois_pontos"
#define TK_PONTO_VIRGULA                        "ponto_virgula"
#define TK_VIRGULA                              "virgula"
#define TK_PONTO                                "ponto"
#define TK_KEYWORD                              "palavra_reservada"
#define TK_NUM_INTEIRO                          "num_inteiro"
#define TK_NUM_REAL                             "num_real"

/*TOKENS OPERADORES*/
#define TK_OP_DIVISAO                           "operador_divisao"
#define TK_OP_DIVISAO_ATRIBUICAO                "operador_divisao_atribuicao"
#define TK_OP_MAIS                              "operador_mais"
#define TK_OP_INCREMENTO                        "operador_incremento"
#define TK_OP_SOMA_ATRIBUICAO                   "operador_soma_atribuicao"
#define TK_OP_MENOS                             "operador_menos"
#define TK_OP_DECREMENTO                        "operador_decremento"
#define TK_OP_SUBTRACAO_ATRIBUICAO              "operador_subtracao_atribuicao"
#define TK_OP_MULTIPLICACAO                     "operador_multiplicacao"
#define TK_OP_MULTIPLICACAO_ATRIBUICAO          "operador_multiplicacao_atribuicao"
#define TK_OP_ATRIBUICAO                        "operador_atribuicao"
#define TK_OP_IGUAL                             "operador_igual"
#define TK_OP_XOR_BIT_A_BIT                     "operador_xor_bit_a_bit"
#define TK_OP_XOR_BIT_A_BIT_ATRIBUICAO          "operador_xor_bit_a_bit_atribuicao"
#define TK_OP_OR_BIT_A_BIT                      "operador_or_bit_a_bit"
#define TK_OP_OR_BIT_A_BIT_ATRIBUICAO           "operador_or_bit_a_bit_atribuicao"
#define TK_OP_OR                                "operador_or"
#define TK_OP_AND_BIT_A_BIT                     "operador_and_bit_a_bit"
#define TK_OP_AND_BIT_A_BIT_ATRIBUICAO          "operador_and_bit_a_bit_atribuicao"
#define TK_OP_AND                               "operador_and"
#define TK_OP_DIFERENTE                         "operador_diferente"
#define TK_OP_NOT                               "operador_not"
#define TK_OP_MODULO                            "operador_modulo"
#define TK_OP_MODULO_ATRIBUICAO                 "operador_modulo_atribuicao"
#define TK_OP_MENOR                             "operador_menor"
#define TK_OP_MENOR_IGUAL                       "operador_menor_igual"
#define TK_OP_DESLOCAMENTO_LEFT                 "operador_deslocamento_left"
#define TK_OP_DESLOCAMENTO_LEFT_ATRIBUICAO      "operador_deslocamento_left_atribuicao"
#define TK_OP_MAIOR                             "operador_maior"
#define TK_OP_MAIOR_IGUAL                       "operador_maior_igual"
#define TK_OP_DESLOCAMENTO_RIGHT                "operador_deslocamento_right"
#define TK_OP_DESLOCAMENTO_RIGHT_ATRIBUICAO     "operador_deslocamento_right_atribuicao"
#define TK_OP_COMPLEMENTO_BIT_A_BIT             "operador_complemento_bit_a_bit"

//ERROS DO LEXEMA
#define TK_ERRO                                 "erro lexico"
#define TK_CARACTERE_INVALIDO                   "caractere_invalido"

#define EOF 			                        "final_arquivo"

#endif // TOKEN_H_INCLUDED
